var game = new Phaser.Game(1500, 1000, Phaser.AUTO);
game.state.add('Load', boil.Load);
game.state.add('Menu', boil.Menu);
game.state.add('start', boil.start);
game.state.add('start1', boil.start1);
game.state.add('Play', boil.Play);
game.state.add('infected', boil.infected);
game.state.add('endGame', boil.endGame);
game.state.add('firstenter', boil.firstenter);
game.state.add('Bossu', boil.Bossu);
game.state.add('GameOver', boil.GameOver);
game.state.start('Load'); 
